### ISSUE TITLE
Fix these issues

### ISSUE THREAD

**Issue by kcpradyp** [tdipendra/Task#5]
- [ ] https://prnt.sc/nme16t (why do you think these are links)

- [ ] https://prnt.sc/nme1rv (bad semantics)

- [ ] https://prnt.sc/nme25p (doesnot look awkward)

- [ ] why so poor with indentations

- [ ] No consistency in html tags h1>h5>h4>h2 there is no hierarchy

**Comment by tdipendra** [comment]
Issue / why do you think these are links
Replaced  anchor link  with button because these button will change the images lol .

Issue-2 / bad semantic
I think this is due to ed_task nature it demands like this lol. 

Issue-3 / doesn't look awkward
Solved this problem using lowercase words for naming folder and images.

Issue-4 / why so poor with indentations
Solved this issue.

Issue-5 / No consistency in html tags h1>h5>h4>h2 there is no hierarchy
Nature of ed_Task doesn't demand html heading tags hierarchy lol.
